# Generated by Django 3.0.5 on 2020-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
