# Generated by Django 3.0.5 on 2020-05-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='enrollment_no',
            new_name='user',
        ),
    ]
