# Generated by Django 3.0.5 on 2020-05-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200515_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_profile_pic.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
