# Generated by Django 3.0.6 on 2020-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200418_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
