# Generated by Django 3.0.5 on 2020-07-13 13:37

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20200523_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=djrichtextfield.models.RichTextField(verbose_name='question'),
        ),
    ]
