# Generated by Django 3.0.5 on 2020-07-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200713_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interests',
            new_name='Batch',
        ),
    ]
